---
- name: update hostname
  command: "hostname {{ hostname }}"

- name: delete dhcp leases
  file:
    path: /var/lib/dhcp/dhclient.leases
    state: absent
  loop:
    - /var/lib/dhcp/dhclient.leases
    - /var/lib/dhcpcd5/dhcpcd-eth0.lease
