---
- name: Create Homeassistant folder on Pi.
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ container_name }}"
    state: directory
    mode: 0755
  become: false

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "homeassistant/home-assistant:stable"
    hostname: "{{ inventory_hostname }}"
    privileged: true
    pull: yes
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "/home/{{ username }}/{{ container_name }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
  tags:
    - update
