---
- hosts: rpi
  become: true

  pre_tasks:
    - set_fact:
        install_docker: "{{ enable_pihole }} or {{ enable_homeassistant }} or {{ enable_trade_bot }}"

  roles:
    - role: essential
      tags:
        - essential

    - role: network
      tags:
        - network

    - role: docker
      when: install_docker
      tags:
        - docker

    - role: containers/pihole
      when: enable_pihole
      tags:
        - pihole
        - containers

    - role: containers/homeassistant
      when: enable_homeassistant
      tags:
        - homeassistant
        - smarthome
        - containers

    - role: containers/trade-bot
      when: enable_trade_bot
      tags:
        - trade-bot
        - containers

    - role: filesystem/mounts
      when: enable_samba
      tags:
        - mounts
        - filesystem

    - role: sprat.mergerfs
      when: enable_samba
      tags:
        - mergerfs
        - filesystem

    - role: filesystem/samba
      when: enable_samba
      tags:
        - samba
        - filesystem

  tasks:
    - name: Prune everything
      community.docker.docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
      when: "'update' in ansible_run_tags"
      tags:
        - update

    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory

    - name: reboot
      reboot:
        msg: Rebooting due to updates
        test_command: ping -c 4 "{{ mac_address_mapping[hostvars[inventory_hostname].ansible_default_ipv4.macaddress].ip }}"
