---
- hosts: rpi
  become: true

  roles:
    - role: essential
      tags:
        - essential

    - role: network
      tags:
        - network

    - role: docker
      tags:
        - docker

    - role: containers/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole
        - containers

    - role: containers/homeassistant
      when: enable_homeassistant | default(False)
      tags:
        - homeassistant
        - smarthome
        - containers

    - role: containers/trade-bot
      when: enable_trade_bot | default(False)
      tags:
        - trade-bot
        - containers

    - role: filesystem/mounts
      when: enable_samba | default(False)
      tags:
        - mounts
        - filesystem

    - role: sprat.mergerfs
      when: enable_samba | default(False)
      tags:
        - mergerfs
        - filesystem

    - role: filesystem/samba
      when: enable_samba | default(False)
      tags:
        - samba
        - filesystem

  tasks:
    - name: Prune everything
      community.docker.docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
      when: "'update' in {{ ansible_run_tags }}"
      tags:
        - update

    - name: reboot
      reboot:
        msg: Rebooting due to updates
        test_command: ping -c 4 "{{ mac_address_mapping[hostvars[inventory_hostname].ansible_default_ipv4.macaddress].ip }}"
