- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "UUID={{ item.uuid }}"
    fstype: ntfs
    state: mounted
    passno: "2"
  loop: "{{ disks }}"
  when: disks[0] is defined
