---
- name: Set the current MAC address for eth0.
  set_fact:
    mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Set variables based on eth0 MAC address.
  set_fact:
    hostname: "{{ mac_address_mapping[mac_address].name }}"
    ip_address: "{{ mac_address_mapping[mac_address].ip }}"

- name: Set up networking-related files.
  template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: hosts.j2, dest: /etc/hosts }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf }
  notify:
    - update hostname
    - delete dhcp leases
  when: ansible_default_ipv4.network != ip_address

- name: Disable bluetooth
  systemd:
    state: stopped
    name: "{{ item }}"
  loop:
    - bluetooth
    - hciuart

- name: Set up Wifi
  systemd:
    state: "{{ 'started' if enable_wifi else 'stopped' }}"
    name: wpa_supplicant
