---
- name: Create Pi-hole folder on Pi.
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ container_name }}"
    state: directory
    mode: 0755
  become: false

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: pihole/pihole:latest
    hostname: "{{ inventory_hostname }}"
    privileged: yes
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env:
      TZ: '{{ timezone }}'
      WEBPASSWORD: '{{ pihole_password }}'
      ServerIP: '{{ ansible_facts["default_ipv4"]["address"] }}'
    dns_servers:
      - 127.0.0.1
      - 8.8.8.8
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
