---
- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    state: latest
    name: "{{ docker_deps }}"

- name: Check if Docker is already present.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script.
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
    state: present
    executable: pip

- name: Ensure Docker is started.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose using Pip.
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip

- name: Ensure {{ username }} user is added to the docker group.
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true

# reset_connection doesn't support conditionals.
- name: Reset connection so docker group is picked up.
  meta: reset_connection